### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by NEUCFgod** [skedia4/vehicle-pedestrian-interactions#1]
Hello，there is a error. How to solve it，thanks
(rlveh) D:\study\project\vpi\vehicle-pedestrian-interactions\src>python main_eval.py     
D:\common\Anaconda\envs\rlveh\lib\site-packages\gym\core.py:27: UserWarning: WARN: Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+
  "Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+"
Traceback (most recent call last):
  File "main_eval.py", line 238, in <module>
    main_eval(device)
  File "main_eval.py", line 65, in main_eval
    env = gym.make(env_name)
  File "D:\common\Anaconda\envs\rlveh\lib\site-packages\gym\envs\registration.py", line 640, in make
    env = env_creator(**_kwargs)
  File "d:\study\project\vpi\vehicle-pedestrian-interactions\gym-pas\gym_pas\envs\pas_env.py", line 44, in __init__
    self.filepath = self.all_files[self.file_index]
IndexError: list index out of range

**Comment by NEUCFgod** [comment]
When I run ‘python main,py’，there still exists the problem
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    main()
  File "main.py", line 71, in main
    env = gym.make(env_name)
  File "D:\common\Anaconda\envs\rlveh\lib\site-packages\gym\envs\registration.py", line 640, in make
    env = env_creator(**_kwargs)
  File "d:\study\project\vpi\vehicle-pedestrian-interactions\gym-pas\gym_pas\envs\pas_env.py", line 44, in __init__
    self.filepath = self.all_files[self.file_index]
IndexError: list index out of range
